[package]
name = "oracle"
version = "1.0.0"
edition = "2018"
authors = ['Bit Country Developer']
# description = "A pallet that demonstrates many aspects of offchain workers"
license = "GPL-3.0-or-later"

[dependencies]
parity-scale-codec = { default-features = false, features = ['derive'], version = '2.0.1' }
parking_lot = "0.10.0"
alt_serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, git = "https://github.com/serde-rs/json", features = ["alloc"] }



# Substrate packages
# sp-runtime = { version = "2.0.0", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
# sp-runtime = { version = "2.0.0", default-features = false }
sp-std = {  git = "https://github.com/paritytech/substrate", default-features = false }
frame-system = { default-features = false, version = "3.0.0" }
frame-support = {default-features = false, version = "3.0.0" }
pallet-aura = { default-features = false, version = "3.0.0"}
pallet-balances = { default-features = false, version = "3.0.0" }
pallet-grandpa = { default-features = false, version = "3.0.0"}
pallet-randomness-collective-flip = { default-features = false, version = "3.0.0"}
pallet-timestamp = {  default-features = false, version = "3.0.0"}
pallet-transaction-payment = { default-features = false, version = "3.0.0"}
# frame-executive = { version = "2.0.0", default-features = false, version = "3.0.0"}
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { default-features = false, version = "3.0.0"}
sp-block-builder = { default-features = false, version = "3.0.0"}
sp-consensus-aura = { default-features = false, version = "0.9.0" }
sp-core = { default-features = false, version = "3.0.0" }
sp-inherents = { default-features = false, version = "3.0.0" }
sp-io = { default-features = false, version = "3.0.0" }
sp-offchain = { default-features = false, version = "3.0.0" }
sp-session = { default-features = false, version = "3.0.0"}
sp-transaction-pool = { default-features = false, version = "3.0.0"}
sp-version = { default-features = false, version = "3.0.0"}
primitives = { package = "bit-country-primitives", path = "../primitives", default-features = false }

[features]
default = ['std']
std = [
	'frame-support/std',
	'frame-system/std',
	'parity-scale-codec/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
]