[package]
authors = ['BitCountry Developers <https://mvp.studio>']
build = 'build.rs'
description = 'A decentralised world powered by economy.'
edition = '2018'
homepage = 'https://bit.country'
license = 'Unlicense'
name = 'bitcountry-parachain'
repository = 'https://github.com/bit-country/Bit-Country-Blockchain/'
version = '0.0.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
hex-literal = "0.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = { version = "15.0.0"}
sc-rpc = {version = "3.0.0"}
sp-api = { version = "3.0.0" }
sp-consensus = { version = "0.9.0" }
sp-consensus-babe = { version = "0.9.0" }
sp-core = { version = "3.0.0" }
sp-finality-grandpa = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-chain-spec = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sc-telemetry = { version = "3.0.0" }
sc-service = { version = "0.9.0" }
sc-executor = { version = "0.9.0" }
sc-consensus = { version = "0.9.0" }
sc-consensus-babe = { version = "0.9.0" }
sc-consensus-manual-seal = { version = "0.9.0" }
sc-consensus-slots = { version = "0.9.0" }
sc-transaction-pool = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }
sc-network = { version = "0.9.0" }
frame-benchmarking = { version = "3.0.0" }
sp-trie = { version = "3.0.0" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.9.0"}
substrate-frame-rpc-system = { version = "3.0.0"}
sp-block-builder = { version = "3.0.0" }
frame-system-rpc-runtime-api = { version = "3.0.0" }
pallet-contracts-rpc = { version = "3.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0" }
sp-offchain = { version = "3.0.0" }
sp-session = { version = "3.0.0" }
sp-storage = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-std = { version = "3.0.0" }
sc-rpc-api = {version = "0.9.0"}
pallet-transaction-payment-rpc = {version = "3.0.0"}
bit-country-primitives = { path = "../pallets/primitives" }
bitcountry-runtime = { path = "../runtime" }
sc-keystore = {version = "3.0.0"}

[[bin]]
name = "bitcountry-parachain"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tokio = { version = "0.2.13", features = ["macros"] }

[build-dependencies]
substrate-build-script-utils = { default-features = false, version = "3.0.0"}